// <auto-generated />
namespace FlossMVCApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeinttostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeinttostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201807130035051_change int to string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
